/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-06-28 08:53:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import teatapi1.Add;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.SQLException;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>My JSP 'listPerson.jsp' starting page</title>\n");
      out.write("\t\t<meta http-equiv=\"pragma\" content=\"no-cache\">\n");
      out.write("\t\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\n");
      out.write("\t\t<meta http-equiv=\"expires\" content=\"0\">\n");
      out.write("\t\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\n");
      out.write("\t\t<meta http-equiv=\"description\" content=\"This is my page\">\n");
      out.write("\t\t<style type=\"text/css\">body, td, th, input {font-size:12px; text-align:center; }</style>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\n");
      out.write("\t\t<table align=right>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\n");
      out.write("\t\t\t\t<td><a href=\"addPerson.jsp\">\n");
      out.write("\t\t\t\t");

				int aa = 5;
				int bb =3;
				Add ad = new Add();
				int cc= ad.addnumber(aa,bb);
				out.println(cc);
				
      out.write("</a>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<br />\n");
      out.write("\t\t<br />\n");

	Connection conn = null;
	Statement stmt = null;
	ResultSet rs = null;
	
	try{
		// 註冊 MySQL 驅動. 也可以使用下面兩種方式的任一種
		DriverManager.registerDriver(new com.mysql.jdbc.Driver());
		//new com.mysql.jdbc.Driver();
		//Class.forName("com.mysql.jdbc.Driver").newInstance();
		
		// 獲得資料庫連接。 三個參數分別為 連接URL，使用者名稱，密碼
		conn = DriverManager.getConnection(
							"jdbc:mysql://localhost:3306/member_database", 
							"root", 
							"801230");
		
		// 獲得 Statement。 Statement 對像用於執行 SQL。相當於控制台。
		stmt = conn.createStatement();
		String str=" select a.order_key,a.member,a.order_time,a.order_remark,b.name,c.product,c.product_number,d.product_name,d.product_price " ;
		str+=" from order_table a ";
		str+=" inner join member_table b ";
		str+=" on a.member =b.member ";
		str+=" inner join order_schedule_table c ";
		str+=" on a.order_key =c.order_key";
		str+=" inner join product_table d";
		str+=" on c.product =d.product";
		
				// 使用 Statement 執行 SELECT 敘述。傳回結果集。
		rs = stmt.executeQuery(str);	

      out.write("\n");
      out.write("\t\t<form action=\"operatePerson.jsp\" method=get>\n");
      out.write("\t\t\t<table bgcolor=\"#CCCCCC\" cellspacing=1 cellpadding=5 width=100%>\n");
      out.write("\t\t\t\t<tr bgcolor=#DDDDDD>\n");
      out.write("\t\t\t\t\t<th></th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\tID\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t訂單主表\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t訂單時間\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t訂單備註\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t姓名\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t訂單明細表\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t商品\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t商品名稱\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t商品價格\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t");

					// 檢查結果集。rs.next() 傳回結果集中是否還有下一條記錄。如果有，自動捲動到下一條記錄並傳回 true
					while (rs.next())
					{

						
						
						
						//member varchar
					//	name varchar
						//sex varchar
						//phone varchar
						//address varchar
						//order_schedule varchar
						//order_key varchar
						//product varchar
						//product_number int
					//	order_time datetime
				//		order_remark varchar
			//			product varchar
		//				product_name varchar
	//					product_description varchar
//						product_price int



						
						
						
						
						int order_key = rs.getInt("order_key"); // 整形類型
						int product_price  = rs.getInt("product_price");

						int product_number = rs.getInt("product_number");
						String 	product_name=rs.getString("product_name");
						String member = rs.getString("member"); // 字串類型
						String order_remark = rs.getString("order_remark");
						String name = rs.getString("name");
						//String description = rs.getString("description");
						String product=rs.getString("product");
						Date order_time = rs.getDate("order_time"); // 日期類型，只有日期資訊而沒有時間資訊
						//Timestamp createTime = rs.getTimestamp("create_time"); // 時間戳類型，既有日期又有時間。

						out.println("		<tr bgcolor=#FFFFFF>");
						out.println("	<td><input type=checkbox name=id value=" + order_key 
						+ "></td>");
						out.println("	<td>" + order_key  + "</td>");
						out.println("	<td>" + member + "</td>");
						out.println("	<td>" +order_time + "</td>");
						out.println("	<td>" + order_remark+ "</td>");
						out.println("	<td>" + name + "</td>");
						out.println("	<td>" + product + "</td>");
						out.println("	<td>" + product_number + "</td>");
						out.println("	<td>" + product_name + "</td>");
						
						out.println("	<td>" + product_price+ "</td>");
							//out.println("	<td>" + birthday + "</td>");
						//out.println("	<td>" + description + "</td>");
						//out.println("	<td>" + createTime + "</td>");
						out.println("	<td>");
						out.println("		<a href='operatePerson.jsp?action=del&id="
						+ order_key + "' onclick='return confirm(\"確定刪除該記錄？\")'>刪除</a>");
						out.println("		<a href='operatePerson.jsp?action=edit&id="
						+ order_key + "'>修改</a>");
						out.println("	</td>");
						out.println("		</tr>");

					}
				
      out.write("\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<table align=left>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<input type='hidden' value='del' name='action'>\n");
      out.write("\t\t\t\t\t\t<a href='#'\n");
      out.write("\t\t\t\t\t\t\tonclick=\"var array=document.getElementsByName('id');for(var i=0; i<array.length;\n");
      out.write("\t\t\t\t\t\t\ti++){array[i].checked=true;}\">全選</a>\n");
      out.write("\t\t\t\t\t\t<a href='#'\n");
      out.write("\t\t\t\t\t\t\tonclick=\"var array=document.getElementsByName('id');for(var i=0; i<array.length;\n");
      out.write("\t\t\t\t\t\t\ti++){array[i].checked=false;}\">取消全選</a>\n");
      out.write("\t\t\t\t\t\t<input type='submit'\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return confirm('即將刪除所選擇的記錄。是否刪除？'); \" value='刪除'>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</form>\n");

	}catch(SQLException e){
		out.println("發生了例外：" + e.getMessage());
		e.printStackTrace();
	}finally{
			// 關閉
			if(rs != null)
				rs.close();
			if(stmt != null)
				stmt.close();
			if(conn != null)
				conn.close();
	}

      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
